version: '3.8'
services:
  # app:
  #   build:
  #     context: '.'
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - mysql
  #   environment:
  #     - DATABASE_URL=mysql://root:${DB_PASSWORD}@mysql:3306/${DB_DATABASE}
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - '3306:3306'
volumes:
  mysql:
